"""Read-only MCP facade over the same GraphSearcher used by the local search CLI.

Pagination changes delivery only. Search membership and graph traversal remain owned
by GraphSearcher; original text is never regenerated by an LLM.
"""
from __future__ import annotations

import hashlib
import json
import re
import time
from datetime import date

from src.search.graph_searcher import GraphSearcher

INTENT_TYPES = ("law", "case", "ruling", "tribunal", "treaty", "annex")
BUCKET_TYPES = {
    "seed_articles": "article", "delegated_articles": "article",
    "referenced_articles": "article", "cases": "case", "tribunals": "case",
    "rulings": "ruling", "interpretations": "interpretation", "basic_rules": "basic_rule",
    "amendments": "amendment", "applicability_evidence": "amendment",
    "cited_versions": "article_version", "treaty_articles": "treaty_article", "annexes": "annex",
}
NODE_TYPES = {
    "article": ("Article", "article_id"), "article_version": ("ArticleVersion", "version_id"),
    "case": ("Case", "case_id"), "ruling": ("Ruling", "ruling_id"),
    "interpretation": ("Interpretation", "interp_id"), "basic_rule": ("BasicRule", "rule_id"),
    "amendment": ("Amendment", "amendment_id"), "annex": ("Annex", "annex_id"),
    "treaty_article": ("TreatyArticle", "treaty_article_id"),
}
BODY_FIELDS = {
    "article": ("article_content",), "article_version": ("article_content",),
    "case": ("full_content", "full_text", "content", "body", "case_holding", "ruling_summary"),
    "ruling": ("full_content", "full_text", "content", "body", "answer_summary", "query_summary"),
    "interpretation": ("full_text", "full_content", "content", "body"),
    "basic_rule": ("rule_content", "content"), "annex": ("content", "full_text"),
    "amendment": ("full_content", "content", "enforcement_text", "application_text", "transitional_text"),
    "treaty_article": ("article_content", "content_ko", "content", "content_en"),
}
SUMMARY_FIELDS = {"case_holding", "ruling_summary", "answer_summary", "query_summary"}
META_FIELDS = (
    "article_id", "version_id", "article_number", "article_title", "law_id", "law_name",
    "article_type", "is_current", "verified", "source_verified", "deleted", "is_deleted",
    "case_id", "case_number", "case_name", "court_name", "court_type", "case_url",
    "ruling_id", "ruling_number", "ruling_title", "ruling_org", "ruling_url",
    "interp_id", "interp_number", "interp_title", "interp_url", "reply_org",
    "source_doc_number", "department_doc_number", "rule_id", "rule_number", "rule_title",
    "amendment_id", "promulgation_number", "annex_id", "annex_number", "annex_title",
    "treaty_article_id", "treaty_name", "country", "source_url", "hwp_url", "pdf_url",
    "source_snapshot", "source_projection_snapshot", "source_projection_sha256",
    "enforcement_date", "effective_date", "valid_from", "valid_to", "ruling_date", "reply_date",
    "promulgation_date", "applies_note", "applies_source", "edition_year", "temporal_resolution",
    "applicability_status", "applicable_date", "resolved_version_id", "reference_semantics",
)
ORIGINAL_LIMIT = 12000
MAX_BODY_PAGE = 24000
NOTICE = (
    "관계 인용은 적용 확정이 아닙니다. 문서 작성·선고일과 법령 적용 시점을 구분하세요. "
    "unresolved 또는 적용버전 미확인은 현행 조문으로 보충하지 않습니다. "
    "원문은 DB 적재 텍스트이며 summary_only는 전문이 없는 요지입니다."
)


def law_file_url(url):
    """별표·서식 파일 주소 — 수집값이 법제처 상대경로(/LSW/flDownload.do?flSeq=…)라 절대주소로 준다."""
    if url.startswith("//"):
        return "https:" + url
    if re.match(r"https?://", url, re.I):
        return re.sub(r"^http://", "https://", url, flags=re.I)
    return "https://www.law.go.kr" + ("" if url.startswith("/") else "/") + url


def _integer(value, name, *, minimum=0, maximum=100000):
    if isinstance(value, bool) or not isinstance(value, int) or not minimum <= value <= maximum:
        raise ValueError(f"{name}: {minimum}~{maximum} 정수가 필요합니다.")
    return value


def _date(value):
    if not isinstance(value, str):
        raise ValueError("as_of: YYYY-MM-DD 또는 YYYYMMDD 날짜가 필요합니다.")  # noqa: TRY004
    if not re.fullmatch(r"(?:\d{8}|\d{4}-\d{2}-\d{2})", value):
        raise ValueError("as_of: YYYY-MM-DD 또는 YYYYMMDD 날짜가 필요합니다.")
    normalized = value.replace("-", "")
    if len(normalized) != 8 or not normalized.isdigit():
        raise ValueError("as_of: YYYY-MM-DD 또는 YYYYMMDD 날짜가 필요합니다.")
    try:
        date.fromisoformat(f"{normalized[:4]}-{normalized[4:6]}-{normalized[6:]}")
    except ValueError as exc:
        raise ValueError("as_of: 존재하지 않는 날짜입니다.") from exc
    return normalized


def _arguments(args, allowed):
    if not isinstance(args, dict) or set(args) - set(allowed):
        raise ValueError("지원하지 않는 인자입니다.")


def validate_search(args):
    _arguments(args, ("search_intents", "as_of", "offset", "limit", "result_set_id"))
    token = args.get("result_set_id")
    if token is not None and (not isinstance(token, str) or not re.fullmatch(r"[a-f0-9]{64}", token)):
        raise ValueError("result_set_id는 이전 응답의 검색 집합 식별자여야 합니다.")
    intents = args.get("search_intents")
    if not isinstance(intents, dict) or not intents or set(intents) - set(INTENT_TYPES):
        raise ValueError("search_intents에는 law/case/ruling/tribunal/treaty/annex 배열을 지정하세요.")
    normalized = {}
    for key, values in intents.items():
        if not isinstance(values, list) or len(values) > 3:
            raise ValueError(f"{key}: 검색 의도는 최대 3개 문자열 배열입니다.")
        if any(not isinstance(v, str) or not v.strip() or len(v) > 300 for v in values):
            raise ValueError(f"{key}: 각 검색 의도는 1~300자 문자열입니다.")
        normalized[key] = list(dict.fromkeys(v.strip() for v in values))
    if not 1 <= sum(map(len, normalized.values())) <= 8:
        raise ValueError("검색 의도는 전체 1~8개까지 지정할 수 있습니다.")
    offset = _integer(args.get("offset", 0), "offset")
    limit = _integer(args.get("limit", 10), "limit", minimum=1, maximum=25)
    as_of = _date(args["as_of"]) if "as_of" in args else None
    return normalized, offset, limit, as_of


def original_text(evidence_type, evidence_id, node, *, offset=0, limit=ORIGINAL_LIMIT, source_field=None):
    fields = BODY_FIELDS[evidence_type]
    available = [f for f in fields if isinstance(node.get(f), str) and node[f].strip()]
    if source_field is not None and source_field not in fields:
        raise ValueError("지원하지 않는 원문 필드입니다.")
    selected = source_field or next(iter(available), None)
    # These are separate original supplementary provisions. Keep all three when
    # no complete Amendment body exists instead of silently keeping only enforcement.
    if evidence_type == "amendment" and source_field is None and selected in fields[2:]:
        selected = "supplementary_provisions"
        text = "\n\n".join(node[f] for f in fields[2:] if f in available)
    else:
        text = node.get(selected, "") if selected else ""
        text = text if isinstance(text, str) else ""
    kind = "missing" if not text else "summary_only" if selected in SUMMARY_FIELDS else "original"
    chunk = text[offset:offset + limit]
    next_offset = offset + len(chunk) if offset + len(chunk) < len(text) else None
    continuation = None
    if next_offset is not None:
        arguments = {"evidence_type": evidence_type, "evidence_id": evidence_id,
                     "offset": next_offset, "limit": limit}
        if source_field:
            arguments["source_field"] = source_field
        continuation = {"tool": "get_evidence", "arguments": arguments}
    return {"text": chunk, "kind": kind, "source_field": selected,
            "available_fields": available, "full_text_available": bool(text) and kind == "original",
            "offset": offset, "total_chars": len(text), "truncated": next_offset is not None,
            "next_offset": next_offset, "continuation": continuation}


def temporal_metadata(node):
    """No date inference: publication/decision date is not a validity interval."""
    return {
        "document_date": node.get("ruling_date") or node.get("reply_date") or node.get("promulgation_date"),
        "enforcement_date": node.get("enforcement_date") or node.get("effective_date"),
        "valid_from": node.get("valid_from"), "valid_to": node.get("valid_to"),
        "temporal_resolution": node.get("temporal_resolution") or "unresolved",
        "resolved_version_id": node.get("resolved_version_id"),
        "resolved_version_ids": list(dict.fromkeys(v["resolved_version_id"]
             for v in node.get("resolved_versions", []) if v.get("resolved_version_id"))),
        "applicability_status": node.get("applicability_status") or "unresolved",
        "applicable_date": node.get("applicable_date"),
        "applies_note": node.get("applies_note"), "applies_source": node.get("applies_source"),
        "edition_year": node.get("edition_year"),
    }


class _SearchConsole:
    def __init__(self):
        self.warnings = []

    def print(self, message, *args, **kwargs):
        text = str(message)
        if "실패" in text or "스킵" in text:
            self.warnings.append(text)


class PublicGraphSearch:
    def __init__(self, execute_query, *, searcher_factory=GraphSearcher):
        self._execute_query = execute_query
        self._searcher_factory = searcher_factory
        self._deadline = time.monotonic() + 45
        self._query_count = 0

    def execute_query(self, query, parameters=None):
        self._query_count += 1
        if self._query_count > 96 or time.monotonic() > self._deadline:
            raise TimeoutError("통합 검색 한도 초과. 검색 의도를 좁혀 주세요.")
        return self._execute_query(query, parameters)

    def _read_nodes(self, evidence_type, ids):
        if not ids:
            return {}
        label, key = NODE_TYPES[evidence_type]
        fields = tuple(dict.fromkeys((*META_FIELDS, *BODY_FIELDS[evidence_type])))
        # Only constants define Cypher identifiers; user IDs remain parameters.
        query = (f"MATCH (n:{label}) WHERE n.{key} IN $ids "
                 "RETURN n {" + ", ".join(f".{f}" for f in fields) + "} AS node")
        return {r["node"][key]: r["node"] for r in self.execute_query(query, {"ids": ids})
                if r.get("node", {}).get(key)}

    def _evidence(self, bucket, kind, node):
        key = NODE_TYPES[kind][1]
        ident = node.get(key) or node.get("resolved_version_id")
        paths = node.get("graph_paths") or []
        source = {k: node[k] for k in META_FIELDS if k in node and k not in BODY_FIELDS[kind]}
        for k in ("hwp_url", "pdf_url"):
            if source.get(k):
                source[k] = law_file_url(source[k])
        if node.get("_content_snapshot"):
            source["source_snapshot"] = node["_content_snapshot"]
        return {"evidence_type": kind, "evidence_id": ident, "result_group": bucket,
                "source": source, "graph_paths": paths,
                "retrieval_method": "graph" if paths else node.get("graph_path") or "direct_lookup",
                "original_text": original_text(kind, ident, node),
                "temporal": temporal_metadata(node)}

    def search(self, args):
        intents, offset, limit, as_of = validate_search(args)
        console = _SearchConsole()
        searcher = self._searcher_factory(self, console=console)
        found = searcher.search_for_query(intents)
        entries = [(bucket, kind, dict(node)) for bucket, kind in BUCKET_TYPES.items()
                   for node in sorted(getattr(found, bucket, []),
                                      key=lambda n: str(n.get(NODE_TYPES[kind][1]) or n.get("resolved_version_id") or ""))]
        identities = [(b, k, n.get(NODE_TYPES[k][1]) or n.get("resolved_version_id"),
                       n.get("_content_snapshot") or n.get("source_snapshot")) for b, k, n in entries]
        result_set_id = hashlib.sha256(json.dumps(
            {"intents": intents, "as_of": as_of, "identities": identities},
            sort_keys=True, ensure_ascii=False, default=str,
        ).encode()).hexdigest()
        if args.get("result_set_id") and args["result_set_id"] != result_set_id:
            raise ValueError("검색 집합이 변경되었습니다. offset=0에서 다시 시작하세요.")
        selected = entries[offset:offset + limit]
        # Re-read selected original records to avoid inheriting legacy projection
        # excerpts. Relationship provenance remains the exact search result's data.
        originals = {}
        for kind in dict.fromkeys(kind for _, kind, _ in selected):
            key = NODE_TYPES[kind][1]
            ids = list(dict.fromkeys(n.get(key) or n.get("resolved_version_id")
                                     for _, k, n in selected if k == kind))
            originals[kind] = self._read_nodes(kind, [i for i in ids if i])
        results = []
        for bucket, kind, searched in selected:
            ident = searched.get(NODE_TYPES[kind][1]) or searched.get("resolved_version_id")
            raw = originals[kind].get(ident, {})
            searched_snapshot = searched.get("_content_snapshot")
            if searched_snapshot and raw.get("source_snapshot") and searched_snapshot != raw["source_snapshot"]:
                raise RuntimeError("검색 중 근거 원문이 갱신되었습니다. 다시 검색하세요.")
            node = {**raw, **searched}
            # Actual node body wins over any earlier excerpt; edge metadata does not.
            for field in BODY_FIELDS[kind]:
                if raw.get(field):
                    node[field] = raw[field]
            node["_content_snapshot"] = raw.get("source_snapshot") or searched.get("_content_snapshot")
            result = self._evidence(bucket, kind, node)
            if as_of and kind == "article" and ident:
                lookup = searcher.get_article_as_of(ident, as_of)
                version = lookup.get("version") or {}
                result["as_of_lookup"] = {
                    **{k: v for k, v in lookup.items() if k != "version"},
                    "version": {k: v for k, v in version.items() if k != "article_content"} or None,
                    "requested_as_of": as_of,
                    "original_text": original_text("article_version", version.get("version_id"), version),
                    "notice": "별도 시점 조회입니다. 검색 경로는 현행 그래프 기준이며, 인용 문서의 적용 버전을 뜻하지 않습니다.",
                }
            results.append(result)
        next_offset = offset + len(selected) if offset + len(selected) < len(entries) else None
        next_page = {"tool": "search_tax", "arguments": {
            **args, "offset": next_offset, "limit": limit, "result_set_id": result_set_id,
        }} if next_offset is not None else None
        return {"schema_version": "tax-graph-evidence-v1", "search_intents": intents,
                "retrieval_engine": "GraphSearcher.search_for_query", "graph_basis": "current",
                "requested_as_of": as_of, "summary": found.to_summary(), "total_results": len(entries),
                "total_results_scope": "local_engine_selected_results",
                "retrieval_limits": "로컬 검색기의 위임 2단계 및 유형별 수집 상한을 동일하게 적용합니다. total_results는 전체 DB 일치 건수가 아닙니다.",
                "offset": offset, "limit": limit, "next_offset": next_offset, "results": results,
                "result_set_id": result_set_id, "next_page": next_page,
                "warnings": console.warnings, "partial": bool(console.warnings), "notice": NOTICE}

    def get_evidence(self, args):
        _arguments(args, ("evidence_type", "evidence_id", "offset", "limit", "source_field"))
        kind, ident = args.get("evidence_type"), args.get("evidence_id")
        if kind not in NODE_TYPES or not isinstance(ident, str) or not 1 <= len(ident) <= 500:
            raise ValueError("search_tax에서 반환된 evidence_type과 evidence_id가 필요합니다.")
        offset = _integer(args.get("offset", 0), "offset", maximum=10000000)
        limit = _integer(args.get("limit", ORIGINAL_LIMIT), "limit", minimum=1, maximum=MAX_BODY_PAGE)
        field = args.get("source_field")
        if field is not None and field not in BODY_FIELDS[kind]:
            raise ValueError("지원하지 않는 원문 필드입니다.")
        node = self._read_nodes(kind, [ident]).get(ident)
        if node is None:
            return {"found": False, "evidence_type": kind, "evidence_id": ident}
        response = self._evidence("direct_lookup", kind, node)
        response["original_text"] = original_text(kind, ident, node, offset=offset, limit=limit, source_field=field)
        response.update({"found": True, "notice": NOTICE})
        return response
